### ISSUE TITLE
Violates the Minecraft TOS

### ISSUE THREAD

**Issue by philippTheCat** [CreeperHost/CreeperHostGui#3] opened 2017-06-01 16:31 UTC
the TOS of minecraft clearly state "Do not make commercial use of anything we've made without our permission.". 

"An Minecraft mod to order a CreeperHost server from in-game" clearly indicates that there is a commercial reasoning behind putting that ad in the game

**Comment by CH-Paul-T** [comment] 2017-06-01 16:37
Writeup here is out of date, mod also provides significant debug information for server owners.

 Also see https://mojang.com/2014/06/lets-talk-server-monetisation/ 
> You are allowed to provide in-game advertising or sponsorship opportunities

**Comment by CH-Paul-T** [comment] 2017-06-01 16:42
Probably best to allow this conversation to continue honestly - But the issue here isn't EULA (A legal entity such as CreeperHost can never be the End User anyway, Commercial Usage is a grey area but as the mod isn't entirely for advertising, should be fine)

What I want is for people to actually open a dialog, I've seen people want to get rid of the bit in the server list, fine, it's already configurable, FTB chose to leave it on, so we'll add a little X so it can be hidden permamently by the end user.

**Comment by philippTheCat** [comment] 2017-06-01 16:54
Yeah, the debug stuff is obviously fine.  Im also talking about the TOS (https://account.mojang.com/terms), which do not only apply to End users, but to legal entities as well. 

"as the mod isn't entirely for advertising, should be fine" im pretty sure this is not how law works. Just because its only part of something bigger doesnt mean its fine. 

"You are allowed to provide in-game advertising or sponsorship opportunities" I interpret this as "hey you can sell advertisement ON your server", not "hey you can advertise your commercial business in our game", but I guess thats open to interpretation

**Comment by CH-Paul-T** [comment] 2017-06-01 16:56
All I know is FTB theirselves contacted Mojang about doing this, and were told it's fine.

Outside of Mojang related issues, which I'm sure Mojang will be the first to tell me if they change their mind regarding what they said to Slowpoke, what issues do you see?

We want feedback, we do not want this to be in your face, at the same time the people we're trying to help are not the ones who know how to set modded servers up, so it needs to be easy to spot etc.

**Comment by philippTheCat** [comment] 2017-06-01 17:00
Well, I can give you the feedback that imho this ad needs to be

- more clearly labeled as ad
- made more obvious that it is NOT an ad by mc, but by FTB

Here's how I reacted to this ad

- wtf?
- why?
- I know where I wont get any server soon

**Comment by CH-Paul-T** [comment] 2017-06-01 17:03
Maybe "Partner" in the top right of the actual "ad"? As it's less an advert, and more a partnership in exchange for hardware/resources, plus ofc we're going to make it really easy to permanently hide, we're working on that now.

**Comment by philippTheCat** [comment] 2017-06-01 17:05
Imho Partner would still suggest that it is a ad BY minecraft, advertising their partner Creeperhost, which is not true. They might be partnered, but its an ad BY the partner, not FOR the partner

**Comment by CH-Paul-T** [comment] 2017-06-01 17:07
True "Modpack Sponsor"? Need to make it provider agnostic because A) The mod has an API for other providers to use and B) it won't always be FTB.

**Comment by philippTheCat** [comment] 2017-06-01 17:12
well, Modpack Sponsor is better I guess, but you could also just allow the provider to set their name through the API.

**Comment by CH-Paul-T** [comment] 2017-06-01 17:15
Likely will in the configuration, but we'd want a 'default' value too, rather than there being nothing there.

**Comment by CH-Paul-T** [comment] 2017-06-01 17:16
Honestly, I truly appreciate your input, we're not evil, sure we want money but as a sustainability thing, this has to be done right or it opens a HUGE issue with what some other providers may do, so we need to keep this kind of feedback coming.

**Comment by StormyMode** [comment] 2017-06-01 20:39
![capture](https://cloud.githubusercontent.com/assets/10284290/26699721/c6aa1d0c-4712-11e7-8fb3-aad84be94cd9.PNG)

**Comment by CH-Paul-T** [comment] 2017-06-01 20:51
But Realms is fine because it's Mojang, right? Not meaning to sound dickish at all by that, it's a genuine question as to if you disagree with Realms too, or not.

> provide in-game advertising opportunities, sponsorships, or product placement for 3rd parties IF they don't degrade or interfere with gameplay

Mojang's documentation conflicts it's self quite a lot, at this point all I can go off is the fact FTB were told directly that doing this was fine.

**Comment by StormyMode** [comment] 2017-06-01 21:10
I don't agree or disagree. However, I do have a problem with you removing my comment and classing it as SPAM just because I made some valid points? 

They do interfere with gameplay, realms is optional - but you're going to hardcode your CH-Mod because of adblockers such as CreeperKiller. It's kind that you've read my suggestions but I think it's fair if all suggestions should be classed too. If you can get Mojang to publicly disclose that confirmation - I'll put my hands up - but as stated in the post [untrustworthy].

For example, if you were an electrician working on a plug-socket and your friend turned off the power - would you trust your friend (FTB)? I certainly wouldn't! I'd check the mains power was off myself. Point being you shouldn't be "passing the buck" to people.

Still not happy about my post being completely disregarded as spam. It was a manual action, not automated.

**Comment by CH-Paul-T** [comment] 2017-06-01 21:13
I like how you assume I did something with your post, I've not been anywhere near CurseForge for the past 2 hours as I've been busy rewriting our curse importer as they pushed an update recently, I've no idea what happened to your post, the first I saw of it was when you posted it here...

And wait, what? Hardcore because of adblockers? Where is that even in any of this? We're adding stuff so blockers like that won't be needed, we're adding features to allow you to block it, I'm unsure where you're getting this from, we have no plans to do anything to counter this CreeperKiller thing, we just wish the person who authored it had instead raised an issue here or maybe opened a pull request to make the ad dismissable.

**Comment by StormyMode** [comment] 2017-06-01 21:17
In all fairness, it's not as bad as assuming the legality your project -- the only reason I'm presuming this is because CH has lost my trust and it's good reputation with its brand identity.

Slowpoke wants to blacklist users from using Modpacks if they're editing the pack (e.g. Removing your mod / or countering it!) which isn't really fair.

**Comment by K-4U** [comment] 2017-06-01 21:18
Slowpoke was joking when he said that.. The mass ammounts of sarcasm in that post made my browser almost explode

**Comment by StormyMode** [comment] 2017-06-01 21:21
That was one of the interpretations brought up, but it also came across as a threat to a whole user base. Misinterpretation is very serious in posts like this and in something as controversial. 

Don't get me wrong, I respect you K-4U, you've done I lot of good things and made some awesome content. I'm aware you've contributed towards this. But the project issues lies between the ideology of CH&FTB.

**Comment by Cloudhunter** [comment] 2017-06-01 21:26
Just a quick note, there are no plans to stop the "creeperkiller" mod working - or to prevent the mod from being disabled (or hardcoding, as mentioned here). Everything in the mod is configurable, by design - and you are also free to disable the mod.

Even if you do want the integration with SIP, you can completely disable the CreeperHost branding and still use it for that purpose - we're not forcing anything on anyone.

I'm going to get out of politics and go back to coding :)

**Comment by darkevilmac** [comment] 2017-06-02 01:19
I feel that this should be made 100% clear on my half, the CreeperKiller mod is primarily a joke. The Readme, logo, and release page apparently hasn't made that clear enough.

It was made as a response to the Reddit post of a very similar title to the CreeperKiller release post.

Do I dislike the CreeperHost mod and feel it oversteps some boundaries? Yes.
Do I think the CreeperKiller mod needs to exist? Of course not, just remove the CreeperHost mod.

**Comment by Cloudhunter** [comment] 2017-09-06 19:42
As conversation has stalled and we're not getting any further with this, gonna close it. Feel free to reply if you have anything to add :)

**Closed by Cloudhunter** 2017-09-06 19:42 UTC
