### ISSUE TITLE
Crash when adding to ATM6

### ISSUE THREAD

**Issue by ElBiggus** [CreeperHost/CreeperHostGui#515] opened 2021-04-03 18:31 UTC
Added MineTogether-1.16.4-4.1.6RC3 to All the Mods 6 (1.16.5; MineTogether listed as compatible with 1.16.5 on CurseForge). Minecraft crashes during load.

Steps to reproduce the behaviour:
1. Install ATM6
2. Add MineTogether-1.16.4-4.1.6RC3
3. Launch game.
4. BOOM!

**Expected behaviour**
Not crashing?

**Versions**
Minecraft: 1.16.5

Forge: 36.0.21

MineTogether: 1.16.4-4.1.6RC3

Crash log attached.
[crash-2021-04-03_19.21.39-client.txt](https://github.com/CreeperHost/MineTogether/files/6253220/crash-2021-04-03_19.21.39-client.txt)

**Comment by gigabit101** [comment] 2021-04-04 01:12
dupe of #487  Fixed in next version

**Closed as completed by gigabit101** 2021-04-04 01:12 UTC
