### ISSUE TITLE
Stoneblock 2 crash caused by MineTogether

### ISSUE THREAD

**Issue by Abasicshot** [CreeperHost/CreeperHostGui#93] opened 2019-08-01 09:34 UTC
Just randomly started to happen after trying to launch my single player world. not much i can really say because it just happened, i haven't done anything but play. 

Crash Report - https://paste.dimdev.org/wewiqeqoha.mccrash

**Comment by Cloudhunter** [comment] 2019-08-06 16:52
Duplicate of #61

**Closed by Cloudhunter** 2019-08-06 16:52 UTC
