### ISSUE TITLE
[Feature]: Config option to disable chat messages

### ISSUE THREAD

**Issue by Saereth** [CreeperHost/CreeperHostGui#632] opened 2022-11-03 20:15 UTC
### Describe the bug

Minetogether chat is printing to the log for everything that everyone says

### Steps to reproduce

Install minetogether (Currently Stoneblock 3 1.0.2) and observe the logs

### Expected behaviour

Not to log every chat within MT's chat scope

### Screenshots

![image](https://user-images.githubusercontent.com/9200909/199825126-1b4f3e4e-a4c8-454d-97f0-0f4e46eb577e.png)

### Version

minetogether-forge-1.18.2-5.2.8

### Minecraft Version

1.18.2

### ModLoader Version

40.1.84

**Comment by covers1624** [comment] 2022-11-04 03:05
I don't think this is really a bug, it was intended that chat goes to the console.

However, I can add a config option to disable/enable it.

**Comment by klugemonkey** [comment] 2022-11-04 05:47
Spamming your mod's content to the log files is outside of the scope of the purpose of log files.  Folks use these log files to look for errors and warning, it is not the place for chat messages.   This should not even be a feature, let alone it should be disabled by default.  But this is just my opinion as a developer.  I think the suggestion on the FTB forums was to just uninstall the mod - probably not what a developer want's to hear about their mod.

**Comment by covers1624** [comment] 2022-11-04 12:22
This is now resolved in MineTogether 6.0.9.

**Closed as completed by covers1624** 2022-11-04 12:22 UTC
Labels: enhancement, added in dev
