### ISSUE TITLE
[Bug]: Not being able to chat

### ISSUE THREAD

**Issue by Elpximso** [CreeperHost/CreeperHostGui#649] opened 2022-11-06 20:35 UTC
### Describe the bug

It seems like im not able to chat, my name is in grey and i have tried to get peoples to respond to no avail. I did get a ban 1 year ago, but it says my account standing is good.

### Steps to reproduce

1. Type in chat.
2. Name is grey and no one responds.

### Expected behaviour

People responding.

### Screenshots

![2022-11-06_21 28 03](https://user-images.githubusercontent.com/49398814/200193653-5ca9a721-3360-4b32-b6e5-be8d6ee8771f.png)

### Version

6.0.9

### Minecraft Version

1.18.2

### ModLoader Version

40.1.84

**Comment by RyanCairns** [comment] 2022-11-06 21:00
Not a bug, Minetogether is just majorly desynced right now.
Name is meant to be gray to you but others can see ya.
Your messages was being sent.
![image](https://user-images.githubusercontent.com/1201230/200194886-8b1a91a3-2810-460d-bda5-7737774591d0.png)

**Comment by Draylynn** [comment] 2022-11-07 02:16
6.0.9 had an issue with chat delay, your message may have appeared later to other chatters, making it seem like they were ignoring you. This seems resolved in 6.0.11 - Please update.

**Closed as completed by Draylynn** 2022-11-07 02:16 UTC
Labels: fixed in dev

**Comment by Elpximso** [comment] 2022-11-07 10:56
> 6.0.9 had an issue with chat delay, your message may have appeared later to other chatters, making it seem like they were ignoring you. This seems resolved in 6.0.11 - Please update.

Coool thank you very much for clearing that up :D
