### ISSUE TITLE
Cannot add people to friends list from chat

### ISSUE THREAD

**Issue by capSAR273** [CreeperHost/CreeperHostGui#424] opened 2020-12-19 03:33 UTC
**Describe the bug**
Cannot add to friend aside from using the friend code feature

**To Reproduce**
Steps to reproduce the behaviour:
1. Have someone "Befriend" you
2. Click the message in chat to Accept
3. Get sad when they don't get added to your friends list

**Expected behaviour**
Adding from the chat should work as intended.

**Screenshots**

**Versions**
Please give all the versions you are using:

Minecraft: 1.16.4

Forge: 35.1.13

MineTogether:MineTogether-1.16.4-4.1.6RC3 (Direwolf20 Pack)

**Additional context**

**Comment by imme40** [comment] 2020-12-20 03:16
**Describe the bug**
Colors don't seem to work on the offical DW20 1.16.4 modpack, and "befriending" people does not seem to work

**To Reproduce**
Steps to reproduce the behaviour:
Chat does not work with colors, besides mods having light blue
Requesting "befriend" of someone sends a message to <Accept>, but nothing happens when clicking any word in that message


**Expected behaviour**
Colors to differentiate people in your mod pack, and different colors to differentiate your version of the modpack

**Screenshots**
I can provide if necessary, but will require coordination of strangers over the internet.

**Versions**
Direwolf20 1.16.4 Modpack
Provided MineTogether Jar: MineTogether-1.16.4-4.1.6RC3.jar

Minecraft:
1.16.4
Forge:
35.1.13
MineTogether:
MineTogether-1.16.4-4.1.6RC3.jar

**Additional context**
Chat functionality
Using MultiMC6 for the launcher, which has an option for downloading FTB instances.

**Comment by gigabit101** [comment] 2020-12-30 12:50
It takes some time for the friend list to be updated due to cacheing, Colours in 1.16 are also fixed in dev

**Closed as completed by gigabit101** 2020-12-30 12:50 UTC
