### ISSUE TITLE
[Request] Force reconnect when disconnected

### ISSUE THREAD

**Issue by billbertking1** [CreeperHost/CreeperHostGui#97] opened 2019-08-07 18:10 UTC
Hi,
So for users with bad internet that cuts out randomly or just MineTogether disconnects, it would be handy to have a "Reconnect" button that forces reconnect as to not have to start the game to reconnect.

**Comment by CH-Paul-T** [comment] 2019-08-07 18:11
Duplicate of #56 - Reconnection logic already implemented in RC.

**Comment by gigabit101** [comment] 2019-09-21 09:36
This should be resolved as of 2.2.0-RC6

**Closed by gigabit101** 2019-09-21 09:36 UTC
Labels: duplicate, fixed in dev
