### ISSUE TITLE
link site times out when code input

### ISSUE THREAD

**Issue by misterboss4** [CreeperHost/CreeperHostGui#677] opened 2022-11-22 01:21 UTC
### Describe the bug

site times out and gives an error

### Steps to reproduce

1. go to minetogether website
2. login
3. goto connect mc account
4. connect to the server
5. put code in site
6. wait til it times out

### Expected behaviour

link mc account with minetogether account

### Screenshots

![Screenshot_20221121_072220](https://user-images.githubusercontent.com/71298766/203191344-78a83e66-0d8e-45f7-a4cb-a66a0d7208f9.png)

### Version

website

### Minecraft Version

none

### ModLoader Version

none

### Additional Information

I'm trying to connect so I can play with a friend

**Comment by Ozzymud** [comment] 2022-11-22 16:47
Just wanted to chime in here, it's not just you misterboss4, I get the exact same error

**Comment by winston9587** [comment] 2022-11-22 23:50
i am having the same problem

**Comment by Matusha** [comment] 2022-11-23 10:48
Same here, I'm guessing link site is down?

**Comment by Jake-E** [comment] 2022-11-23 11:33
This should be fixed.

**Comment by Ozzymud** [comment] 2022-11-23 20:33
Can confirm, is indeed fixed for me at least.

**Comment by DarkShinyGiratina** [comment] 2022-12-04 04:47
Did this break again? The issue isn't closed so I didn't want to start a new one, but I currently can't link my MC account (same issue with the site timing out)

**Closed as completed** 2022-12-12 16:27 UTC
