### ISSUE TITLE
[Bug]: Fabric version doesn't list PolyLib as a dependency in fabric.mod.json

### ISSUE THREAD

**Issue by floral-qua-floral** [CreeperHost/CreeperHostGui#613] opened 2022-08-06 02:27 UTC
### Describe the bug

MineTogether depends on PolyLib, but this dependency is not listed in the fabric.mod.json "depends" section.

### Steps to reproduce

1. Download MineTogether, Fabric API, Architectury, and PolyLib.
2. Set up a profile with MineTogether, Fabric API, and PolyLib, but without Architectury.
3. Attempt to launch the game. Fabric will alert the user as to what mod they need to download, and what mod requires it.
4. Set up a profile with MineTogether, Fabric API, and Architectury, but without PolyLib.
5. Attempt to launch the game. It will simply fail to launch, providing no crash report and an unhelpfully vague error message.

### Expected behaviour

PolyLib should be included in the fabric.mod.json's "depends" section so that the Fabric loader will recognize the missing dependency & provide a clear, useful warning, like it does when Architectury is missing.

### Screenshots

Screenshot of the relevant section of fabric.mod.json:  
![image](https://user-images.githubusercontent.com/49110090/183229927-677de77e-58d2-4541-baf8-ef76dc1f9060.png)

### Version

5.2.8

### Minecraft Version

1.19

### ModLoader Version

Fabric

**Comment by dryter97** [comment] 2022-09-16 19:06
also it tell there is missing files into the error code where polylib is stated

`15:01:21.460
FabricLoader/Mixin
Client Shutdown Thread
Error loading class: net/creeperhost/polylib/client/screen/widget/buttons/DropdownButton (java.lang.ClassNotFoundException: net/creeperhost/polylib/client/screen/widget/buttons/DropdownButton)
15:01:21.461
net.minecraft.client.main.Main
Client Shutdown Thread
Caught previously unhandled exception :
java.lang.RuntimeException: Mixin transformation of net.minecraft.class_408 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:347)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.client.main.Main$2.run(Main.java:177)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	... 13 more
Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: net.creeperhost.polylib.client.screen.widget.buttons.DropdownButton
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:1002)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformDescriptor(MixinTargetContext.java:906)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:608)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 16 more`

**Comment by covers1624** [comment] 2022-11-03 10:24
This has been resolved in MineTogether 6.0.

**Closed as completed by covers1624** 2022-11-03 10:24 UTC
Labels: bug, low priority, 1.18+
