### ISSUE TITLE
Issue from FTB Ultimate Reload upon world load

### ISSUE THREAD

**Issue by tfox83** [CreeperHost/CreeperHostGui#67] opened 2019-04-04 22:39 UTC
https://github.com/FTBTeam/FTB-Ultimate-Reloaded/issues/173

**Comment by Cloudhunter** [comment] 2019-04-05 16:31
Duplicate of #61

**Comment by gigabit101** [comment] 2019-07-03 10:34
closing due to duplicate issue

**Closed by gigabit101** 2019-07-03 10:34 UTC
